
name: Metrics
on:
  # Schedule daily updates
  # schedule: [{cron: "0 0 * * 0"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  # push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
       contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: lutif
          config_timezone: West Central Africa 
          config_display: large
          commits_authoring: omogopeter48@gmail.com 
          plugin_achievements: yes
          plugin_calendar: yes
          plugin_calendar_limit: 3
          plugin_followup: yes
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          plugin_introduction: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_languages: yes
          plugin_languages_ignored: dockerfile, TSQL, EJS, Batchfile, makefile, SCSS, Jupyter Notebook, CSS, HTML
          plugin_licenses: yes
          plugin_lines:  yes
          plugin_notable: no
          plugin_people: yes
          plugin_people_types: contributors
          plugin_repositories: yes
          plugin_repositories_featured: onyedika-glitch/react-touchdown, onyedika-glitch /create-react-rust 
          plugin_topics: yes
          plugin_topics_mode: icons
